export const openApiSpec = {
  openapi: '3.0.3',
  info: { title: 'ClubPaddle API', version: '1.0.0' },
  servers: [{ url: 'http://localhost:4000' }],
  paths: {
    '/public/club/{slug}': { get: { summary: 'Get club by slug' } },
    '/public/availability': { get: { summary: 'Get available slots' } },
    '/public/reservations/hold': { post: { summary: 'Create HOLD reservation' } },
    '/public/reservations/confirm': { post: { summary: 'Confirm HOLD reservation' } },
    '/public/reservations/{id}/summary': { get: { summary: 'Reservation summary + WA links' } },
    '/public/manage': { get: { summary: 'View reservation by manage token' } },
    '/public/manage/cancel': { post: { summary: 'Cancel reservation by manage token' } },
    '/public/manage/reschedule': { post: { summary: 'Reschedule by manage token' } },
    '/public/payments/cash': { post: { summary: 'Register cash payment' } },
    '/public/payments/transfer-notify': { post: { summary: 'Notify manual transfer payment (pending verification)' } },
    '/public/payments/mercadopago/config': { get: { summary: 'Mercado Pago public config' } },
    '/public/payments/mercadopago/preference': { post: { summary: 'Create Mercado Pago preference (card/transfer)' } },
    '/public/payments/mercadopago/card-pay': { post: { summary: 'Pay with card using Mercado Pago tokenized flow' } },
    '/admin/auth/login': { post: { summary: 'Admin login' } },
    '/admin/auth/refresh': { post: { summary: 'Admin refresh token' } },
    '/admin/agenda': { get: { summary: 'Agenda day view' } },
    '/admin/clubs': { get: {}, post: {} },
    '/admin/courts': { get: {}, post: {} },
    '/admin/blocks': { get: {}, post: {} },
    '/admin/pricing': { get: {}, post: {} },
    '/admin/reservations': { get: {}, post: {} },
    '/admin/reservations/{id}/resend-manage-link': { post: {} },
    '/admin/users': { get: {}, post: {} },
    '/admin/backups/create': { post: {} },
    '/admin/backups/restore': { post: {} },
    '/admin/backups/list': { get: {} },
    '/admin/license/status': { get: {} },
    '/admin/license/activate': { post: {} }
  }
};
